<?php
/**
 * BackgroundProcessesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Dimer47\LaravelForgeSdk\ApiException;
use Dimer47\LaravelForgeSdk\Configuration;
use Dimer47\LaravelForgeSdk\FormDataProcessor;
use Dimer47\LaravelForgeSdk\HeaderSelector;
use Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * BackgroundProcessesApi Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BackgroundProcessesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'organizationsServersBackgroundProcessesDestroy' => [
            'application/json',
        ],
        'organizationsServersBackgroundProcessesIndex' => [
            'application/json',
        ],
        'organizationsServersBackgroundProcessesLogShow' => [
            'application/json',
        ],
        'organizationsServersBackgroundProcessesShow' => [
            'application/json',
        ],
        'organizationsServersBackgroundProcessesStore' => [
            'application/json',
        ],
        'organizationsServersBackgroundProcessesUpdate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation organizationsServersBackgroundProcessesDestroy
     *
     * Delete background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesDestroy'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function organizationsServersBackgroundProcessesDestroy($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesDestroy'][0])
    {
        $this->organizationsServersBackgroundProcessesDestroyWithHttpInfo($organization, $server, $background_process, $contentType);
    }

    /**
     * Operation organizationsServersBackgroundProcessesDestroyWithHttpInfo
     *
     * Delete background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesDestroy'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersBackgroundProcessesDestroyWithHttpInfo($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesDestroy'][0])
    {
        $request = $this->organizationsServersBackgroundProcessesDestroyRequest($organization, $server, $background_process, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersBackgroundProcessesDestroyAsync
     *
     * Delete background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesDestroyAsync($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesDestroy'][0])
    {
        return $this->organizationsServersBackgroundProcessesDestroyAsyncWithHttpInfo($organization, $server, $background_process, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersBackgroundProcessesDestroyAsyncWithHttpInfo
     *
     * Delete background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesDestroyAsyncWithHttpInfo($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesDestroy'][0])
    {
        $returnType = '';
        $request = $this->organizationsServersBackgroundProcessesDestroyRequest($organization, $server, $background_process, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersBackgroundProcessesDestroy'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersBackgroundProcessesDestroyRequest($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesDestroy'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersBackgroundProcessesDestroy'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersBackgroundProcessesDestroy'
            );
        }

        // verify the required parameter 'background_process' is set
        if ($background_process === null || (is_array($background_process) && count($background_process) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $background_process when calling organizationsServersBackgroundProcessesDestroy'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/background-processes/{backgroundProcess}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($background_process !== null) {
            $resourcePath = str_replace(
                '{backgroundProcess}',
                ObjectSerializer::toPathValue($background_process),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersBackgroundProcessesIndex
     *
     * List background processes
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;user&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-user&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_user The user that the process is running as. (optional)
     * @param  string|null $filter_site_id The site ID that the process is running for. (optional)
     * @param  string|null $filter_directory The directory that the process is running in. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesIndex'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesIndex200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject
     */
    public function organizationsServersBackgroundProcessesIndex($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_user = null, $filter_site_id = null, $filter_directory = null, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesIndex'][0])
    {
        list($response) = $this->organizationsServersBackgroundProcessesIndexWithHttpInfo($organization, $server, $sort, $page_size, $page_cursor, $filter_user, $filter_site_id, $filter_directory, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersBackgroundProcessesIndexWithHttpInfo
     *
     * List background processes
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;user&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-user&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_user The user that the process is running as. (optional)
     * @param  string|null $filter_site_id The site ID that the process is running for. (optional)
     * @param  string|null $filter_directory The directory that the process is running in. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesIndex'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesIndex200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersBackgroundProcessesIndexWithHttpInfo($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_user = null, $filter_site_id = null, $filter_directory = null, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesIndex'][0])
    {
        $request = $this->organizationsServersBackgroundProcessesIndexRequest($organization, $server, $sort, $page_size, $page_cursor, $filter_user, $filter_site_id, $filter_directory, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesIndex200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesIndex200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesIndex200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersBackgroundProcessesIndexAsync
     *
     * List background processes
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;user&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-user&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_user The user that the process is running as. (optional)
     * @param  string|null $filter_site_id The site ID that the process is running for. (optional)
     * @param  string|null $filter_directory The directory that the process is running in. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesIndexAsync($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_user = null, $filter_site_id = null, $filter_directory = null, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesIndex'][0])
    {
        return $this->organizationsServersBackgroundProcessesIndexAsyncWithHttpInfo($organization, $server, $sort, $page_size, $page_cursor, $filter_user, $filter_site_id, $filter_directory, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersBackgroundProcessesIndexAsyncWithHttpInfo
     *
     * List background processes
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;user&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-user&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_user The user that the process is running as. (optional)
     * @param  string|null $filter_site_id The site ID that the process is running for. (optional)
     * @param  string|null $filter_directory The directory that the process is running in. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesIndexAsyncWithHttpInfo($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_user = null, $filter_site_id = null, $filter_directory = null, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesIndex'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesIndex200Response';
        $request = $this->organizationsServersBackgroundProcessesIndexRequest($organization, $server, $sort, $page_size, $page_cursor, $filter_user, $filter_site_id, $filter_directory, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersBackgroundProcessesIndex'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;user&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-user&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_user The user that the process is running as. (optional)
     * @param  string|null $filter_site_id The site ID that the process is running for. (optional)
     * @param  string|null $filter_directory The directory that the process is running in. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersBackgroundProcessesIndexRequest($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_user = null, $filter_site_id = null, $filter_directory = null, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesIndex'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersBackgroundProcessesIndex'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersBackgroundProcessesIndex'
            );
        }








        $resourcePath = '/orgs/{organization}/servers/{server}/background-processes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page[size]', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_cursor,
            'page[cursor]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_user,
            'filter[user]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_site_id,
            'filter[site_id]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_directory,
            'filter[directory]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersBackgroundProcessesLogShow
     *
     * Get background process log
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesLogShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesLogShow200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject
     */
    public function organizationsServersBackgroundProcessesLogShow($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesLogShow'][0])
    {
        list($response) = $this->organizationsServersBackgroundProcessesLogShowWithHttpInfo($organization, $server, $background_process, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersBackgroundProcessesLogShowWithHttpInfo
     *
     * Get background process log
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesLogShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesLogShow200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersBackgroundProcessesLogShowWithHttpInfo($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesLogShow'][0])
    {
        $request = $this->organizationsServersBackgroundProcessesLogShowRequest($organization, $server, $background_process, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesLogShow200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesLogShow200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesLogShow200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersBackgroundProcessesLogShowAsync
     *
     * Get background process log
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesLogShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesLogShowAsync($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesLogShow'][0])
    {
        return $this->organizationsServersBackgroundProcessesLogShowAsyncWithHttpInfo($organization, $server, $background_process, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersBackgroundProcessesLogShowAsyncWithHttpInfo
     *
     * Get background process log
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesLogShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesLogShowAsyncWithHttpInfo($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesLogShow'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesLogShow200Response';
        $request = $this->organizationsServersBackgroundProcessesLogShowRequest($organization, $server, $background_process, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersBackgroundProcessesLogShow'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesLogShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersBackgroundProcessesLogShowRequest($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesLogShow'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersBackgroundProcessesLogShow'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersBackgroundProcessesLogShow'
            );
        }

        // verify the required parameter 'background_process' is set
        if ($background_process === null || (is_array($background_process) && count($background_process) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $background_process when calling organizationsServersBackgroundProcessesLogShow'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/background-processes/{backgroundProcess}/log';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($background_process !== null) {
            $resourcePath = str_replace(
                '{backgroundProcess}',
                ObjectSerializer::toPathValue($background_process),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersBackgroundProcessesShow
     *
     * Get background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject
     */
    public function organizationsServersBackgroundProcessesShow($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesShow'][0])
    {
        list($response) = $this->organizationsServersBackgroundProcessesShowWithHttpInfo($organization, $server, $background_process, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersBackgroundProcessesShowWithHttpInfo
     *
     * Get background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersBackgroundProcessesShowWithHttpInfo($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesShow'][0])
    {
        $request = $this->organizationsServersBackgroundProcessesShowRequest($organization, $server, $background_process, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersBackgroundProcessesShowAsync
     *
     * Get background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesShowAsync($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesShow'][0])
    {
        return $this->organizationsServersBackgroundProcessesShowAsyncWithHttpInfo($organization, $server, $background_process, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersBackgroundProcessesShowAsyncWithHttpInfo
     *
     * Get background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesShowAsyncWithHttpInfo($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesShow'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response';
        $request = $this->organizationsServersBackgroundProcessesShowRequest($organization, $server, $background_process, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersBackgroundProcessesShow'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersBackgroundProcessesShowRequest($organization, $server, $background_process, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesShow'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersBackgroundProcessesShow'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersBackgroundProcessesShow'
            );
        }

        // verify the required parameter 'background_process' is set
        if ($background_process === null || (is_array($background_process) && count($background_process) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $background_process when calling organizationsServersBackgroundProcessesShow'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/background-processes/{backgroundProcess}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($background_process !== null) {
            $resourcePath = str_replace(
                '{backgroundProcess}',
                ObjectSerializer::toPathValue($background_process),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersBackgroundProcessesStore
     *
     * Create background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateBackgroundProcessRequest $create_background_process_request create_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesStore'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject1
     */
    public function organizationsServersBackgroundProcessesStore($organization, $server, $create_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesStore'][0])
    {
        list($response) = $this->organizationsServersBackgroundProcessesStoreWithHttpInfo($organization, $server, $create_background_process_request, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersBackgroundProcessesStoreWithHttpInfo
     *
     * Create background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateBackgroundProcessRequest $create_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesStore'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersBackgroundProcessesStoreWithHttpInfo($organization, $server, $create_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesStore'][0])
    {
        $request = $this->organizationsServersBackgroundProcessesStoreRequest($organization, $server, $create_background_process_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersBackgroundProcessesStoreAsync
     *
     * Create background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateBackgroundProcessRequest $create_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesStoreAsync($organization, $server, $create_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesStore'][0])
    {
        return $this->organizationsServersBackgroundProcessesStoreAsyncWithHttpInfo($organization, $server, $create_background_process_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersBackgroundProcessesStoreAsyncWithHttpInfo
     *
     * Create background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateBackgroundProcessRequest $create_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesStoreAsyncWithHttpInfo($organization, $server, $create_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesStore'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersBackgroundProcessesStore202Response';
        $request = $this->organizationsServersBackgroundProcessesStoreRequest($organization, $server, $create_background_process_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersBackgroundProcessesStore'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateBackgroundProcessRequest $create_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersBackgroundProcessesStoreRequest($organization, $server, $create_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesStore'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersBackgroundProcessesStore'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersBackgroundProcessesStore'
            );
        }

        // verify the required parameter 'create_background_process_request' is set
        if ($create_background_process_request === null || (is_array($create_background_process_request) && count($create_background_process_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_background_process_request when calling organizationsServersBackgroundProcessesStore'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/background-processes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_background_process_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_background_process_request));
            } else {
                $httpBody = $create_background_process_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersBackgroundProcessesUpdate
     *
     * Update background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\UpdateBackgroundProcessRequest $update_background_process_request update_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesUpdate'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function organizationsServersBackgroundProcessesUpdate($organization, $server, $background_process, $update_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesUpdate'][0])
    {
        $this->organizationsServersBackgroundProcessesUpdateWithHttpInfo($organization, $server, $background_process, $update_background_process_request, $contentType);
    }

    /**
     * Operation organizationsServersBackgroundProcessesUpdateWithHttpInfo
     *
     * Update background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\UpdateBackgroundProcessRequest $update_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesUpdate'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersBackgroundProcessesUpdateWithHttpInfo($organization, $server, $background_process, $update_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesUpdate'][0])
    {
        $request = $this->organizationsServersBackgroundProcessesUpdateRequest($organization, $server, $background_process, $update_background_process_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersBackgroundProcessesUpdateAsync
     *
     * Update background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\UpdateBackgroundProcessRequest $update_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesUpdateAsync($organization, $server, $background_process, $update_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesUpdate'][0])
    {
        return $this->organizationsServersBackgroundProcessesUpdateAsyncWithHttpInfo($organization, $server, $background_process, $update_background_process_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersBackgroundProcessesUpdateAsyncWithHttpInfo
     *
     * Update background process
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\UpdateBackgroundProcessRequest $update_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersBackgroundProcessesUpdateAsyncWithHttpInfo($organization, $server, $background_process, $update_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesUpdate'][0])
    {
        $returnType = '';
        $request = $this->organizationsServersBackgroundProcessesUpdateRequest($organization, $server, $background_process, $update_background_process_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersBackgroundProcessesUpdate'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $background_process The background process ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\UpdateBackgroundProcessRequest $update_background_process_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersBackgroundProcessesUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersBackgroundProcessesUpdateRequest($organization, $server, $background_process, $update_background_process_request, string $contentType = self::contentTypes['organizationsServersBackgroundProcessesUpdate'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersBackgroundProcessesUpdate'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersBackgroundProcessesUpdate'
            );
        }

        // verify the required parameter 'background_process' is set
        if ($background_process === null || (is_array($background_process) && count($background_process) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $background_process when calling organizationsServersBackgroundProcessesUpdate'
            );
        }

        // verify the required parameter 'update_background_process_request' is set
        if ($update_background_process_request === null || (is_array($update_background_process_request) && count($update_background_process_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_background_process_request when calling organizationsServersBackgroundProcessesUpdate'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/background-processes/{backgroundProcess}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($background_process !== null) {
            $resourcePath = str_replace(
                '{backgroundProcess}',
                ObjectSerializer::toPathValue($background_process),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_background_process_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_background_process_request));
            } else {
                $httpBody = $update_background_process_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
