<?php

/**
 * MonitorsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Dimer47\LaravelForgeSdk\ApiException;
use Dimer47\LaravelForgeSdk\Configuration;
use Dimer47\LaravelForgeSdk\FormDataProcessor;
use Dimer47\LaravelForgeSdk\HeaderSelector;
use Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * MonitorsApi Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MonitorsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'organizationsServersMonitorsDestroy' => [
            'application/json',
        ],
        'organizationsServersMonitorsIndex' => [
            'application/json',
        ],
        'organizationsServersMonitorsShow' => [
            'application/json',
        ],
        'organizationsServersMonitorsStore' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation organizationsServersMonitorsDestroy
     *
     * Delete server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsDestroy'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function organizationsServersMonitorsDestroy($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsDestroy'][0])
    {
        $this->organizationsServersMonitorsDestroyWithHttpInfo($organization, $server, $monitor, $contentType);
    }

    /**
     * Operation organizationsServersMonitorsDestroyWithHttpInfo
     *
     * Delete server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsDestroy'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersMonitorsDestroyWithHttpInfo($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsDestroy'][0])
    {
        $request = $this->organizationsServersMonitorsDestroyRequest($organization, $server, $monitor, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation organizationsServersMonitorsDestroyAsync
     *
     * Delete server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsDestroyAsync($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsDestroy'][0])
    {
        return $this->organizationsServersMonitorsDestroyAsyncWithHttpInfo($organization, $server, $monitor, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersMonitorsDestroyAsyncWithHttpInfo
     *
     * Delete server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsDestroyAsyncWithHttpInfo($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsDestroy'][0])
    {
        $returnType = '';
        $request = $this->organizationsServersMonitorsDestroyRequest($organization, $server, $monitor, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersMonitorsDestroy'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersMonitorsDestroyRequest($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsDestroy'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersMonitorsDestroy'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersMonitorsDestroy'
            );
        }

        // verify the required parameter 'monitor' is set
        if ($monitor === null || (is_array($monitor) && count($monitor) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $monitor when calling organizationsServersMonitorsDestroy'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/monitors/{monitor}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($monitor !== null) {
            $resourcePath = str_replace(
                '{monitor}',
                ObjectSerializer::toPathValue($monitor),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersMonitorsIndex
     *
     * List server monitors
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;state&#x60;, &#x60;status&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-state&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_status The status of the monitor. (optional)
     * @param  string|null $filter_state The state of the monitor. (optional)
     * @param  string|null $filter_type The type of the monitor. (optional)
     * @param  string|null $filter_notify The email address to notify when the monitor is in an alert state. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsIndex'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsIndex200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject
     */
    public function organizationsServersMonitorsIndex($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_status = null, $filter_state = null, $filter_type = null, $filter_notify = null, string $contentType = self::contentTypes['organizationsServersMonitorsIndex'][0])
    {
        list($response) = $this->organizationsServersMonitorsIndexWithHttpInfo($organization, $server, $sort, $page_size, $page_cursor, $filter_status, $filter_state, $filter_type, $filter_notify, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersMonitorsIndexWithHttpInfo
     *
     * List server monitors
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;state&#x60;, &#x60;status&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-state&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_status The status of the monitor. (optional)
     * @param  string|null $filter_state The state of the monitor. (optional)
     * @param  string|null $filter_type The type of the monitor. (optional)
     * @param  string|null $filter_notify The email address to notify when the monitor is in an alert state. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsIndex'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsIndex200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersMonitorsIndexWithHttpInfo($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_status = null, $filter_state = null, $filter_type = null, $filter_notify = null, string $contentType = self::contentTypes['organizationsServersMonitorsIndex'][0])
    {
        $request = $this->organizationsServersMonitorsIndexRequest($organization, $server, $sort, $page_size, $page_cursor, $filter_status, $filter_state, $filter_type, $filter_notify, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsIndex200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsIndex200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsIndex200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation organizationsServersMonitorsIndexAsync
     *
     * List server monitors
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;state&#x60;, &#x60;status&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-state&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_status The status of the monitor. (optional)
     * @param  string|null $filter_state The state of the monitor. (optional)
     * @param  string|null $filter_type The type of the monitor. (optional)
     * @param  string|null $filter_notify The email address to notify when the monitor is in an alert state. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsIndexAsync($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_status = null, $filter_state = null, $filter_type = null, $filter_notify = null, string $contentType = self::contentTypes['organizationsServersMonitorsIndex'][0])
    {
        return $this->organizationsServersMonitorsIndexAsyncWithHttpInfo($organization, $server, $sort, $page_size, $page_cursor, $filter_status, $filter_state, $filter_type, $filter_notify, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersMonitorsIndexAsyncWithHttpInfo
     *
     * List server monitors
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;state&#x60;, &#x60;status&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-state&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_status The status of the monitor. (optional)
     * @param  string|null $filter_state The state of the monitor. (optional)
     * @param  string|null $filter_type The type of the monitor. (optional)
     * @param  string|null $filter_notify The email address to notify when the monitor is in an alert state. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsIndexAsyncWithHttpInfo($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_status = null, $filter_state = null, $filter_type = null, $filter_notify = null, string $contentType = self::contentTypes['organizationsServersMonitorsIndex'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsIndex200Response';
        $request = $this->organizationsServersMonitorsIndexRequest($organization, $server, $sort, $page_size, $page_cursor, $filter_status, $filter_state, $filter_type, $filter_notify, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersMonitorsIndex'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  string|null $sort Available sorts are &#x60;state&#x60;, &#x60;status&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-state&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_status The status of the monitor. (optional)
     * @param  string|null $filter_state The state of the monitor. (optional)
     * @param  string|null $filter_type The type of the monitor. (optional)
     * @param  string|null $filter_notify The email address to notify when the monitor is in an alert state. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersMonitorsIndexRequest($organization, $server, $sort = null, $page_size = 30, $page_cursor = null, $filter_status = null, $filter_state = null, $filter_type = null, $filter_notify = null, string $contentType = self::contentTypes['organizationsServersMonitorsIndex'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersMonitorsIndex'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersMonitorsIndex'
            );
        }









        $resourcePath = '/orgs/{organization}/servers/{server}/monitors';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page[size]', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_cursor,
            'page[cursor]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_status,
            'filter[status]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_state,
            'filter[state]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_type,
            'filter[type]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_notify,
            'filter[notify]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersMonitorsShow
     *
     * Get server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject
     */
    public function organizationsServersMonitorsShow($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsShow'][0])
    {
        list($response) = $this->organizationsServersMonitorsShowWithHttpInfo($organization, $server, $monitor, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersMonitorsShowWithHttpInfo
     *
     * Get server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersMonitorsShowWithHttpInfo($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsShow'][0])
    {
        $request = $this->organizationsServersMonitorsShowRequest($organization, $server, $monitor, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation organizationsServersMonitorsShowAsync
     *
     * Get server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsShowAsync($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsShow'][0])
    {
        return $this->organizationsServersMonitorsShowAsyncWithHttpInfo($organization, $server, $monitor, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersMonitorsShowAsyncWithHttpInfo
     *
     * Get server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsShowAsyncWithHttpInfo($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsShow'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response';
        $request = $this->organizationsServersMonitorsShowRequest($organization, $server, $monitor, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersMonitorsShow'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $monitor The monitor ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersMonitorsShowRequest($organization, $server, $monitor, string $contentType = self::contentTypes['organizationsServersMonitorsShow'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersMonitorsShow'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersMonitorsShow'
            );
        }

        // verify the required parameter 'monitor' is set
        if ($monitor === null || (is_array($monitor) && count($monitor) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $monitor when calling organizationsServersMonitorsShow'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/monitors/{monitor}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($monitor !== null) {
            $resourcePath = str_replace(
                '{monitor}',
                ObjectSerializer::toPathValue($monitor),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersMonitorsStore
     *
     * Create server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateMonitorRequest $create_monitor_request create_monitor_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsStore'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject1
     */
    public function organizationsServersMonitorsStore($organization, $server, $create_monitor_request, string $contentType = self::contentTypes['organizationsServersMonitorsStore'][0])
    {
        list($response) = $this->organizationsServersMonitorsStoreWithHttpInfo($organization, $server, $create_monitor_request, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersMonitorsStoreWithHttpInfo
     *
     * Create server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateMonitorRequest $create_monitor_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsStore'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject1, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersMonitorsStoreWithHttpInfo($organization, $server, $create_monitor_request, string $contentType = self::contentTypes['organizationsServersMonitorsStore'][0])
    {
        $request = $this->organizationsServersMonitorsStoreRequest($organization, $server, $create_monitor_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject1',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation organizationsServersMonitorsStoreAsync
     *
     * Create server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateMonitorRequest $create_monitor_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsStoreAsync($organization, $server, $create_monitor_request, string $contentType = self::contentTypes['organizationsServersMonitorsStore'][0])
    {
        return $this->organizationsServersMonitorsStoreAsyncWithHttpInfo($organization, $server, $create_monitor_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersMonitorsStoreAsyncWithHttpInfo
     *
     * Create server monitor
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateMonitorRequest $create_monitor_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersMonitorsStoreAsyncWithHttpInfo($organization, $server, $create_monitor_request, string $contentType = self::contentTypes['organizationsServersMonitorsStore'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersMonitorsStore202Response';
        $request = $this->organizationsServersMonitorsStoreRequest($organization, $server, $create_monitor_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersMonitorsStore'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateMonitorRequest $create_monitor_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersMonitorsStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersMonitorsStoreRequest($organization, $server, $create_monitor_request, string $contentType = self::contentTypes['organizationsServersMonitorsStore'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersMonitorsStore'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersMonitorsStore'
            );
        }

        // verify the required parameter 'create_monitor_request' is set
        if ($create_monitor_request === null || (is_array($create_monitor_request) && count($create_monitor_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_monitor_request when calling organizationsServersMonitorsStore'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/monitors';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_monitor_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_monitor_request));
            } else {
                $httpBody = $create_monitor_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
