<?php
/**
 * RedirectRulesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Dimer47\LaravelForgeSdk\ApiException;
use Dimer47\LaravelForgeSdk\Configuration;
use Dimer47\LaravelForgeSdk\FormDataProcessor;
use Dimer47\LaravelForgeSdk\HeaderSelector;
use Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * RedirectRulesApi Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RedirectRulesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'organizationsServersSitesRedirectRulesDestroy' => [
            'application/json',
        ],
        'organizationsServersSitesRedirectRulesIndex' => [
            'application/json',
        ],
        'organizationsServersSitesRedirectRulesShow' => [
            'application/json',
        ],
        'organizationsServersSitesRedirectRulesStore' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation organizationsServersSitesRedirectRulesDestroy
     *
     * Delete site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesDestroy'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function organizationsServersSitesRedirectRulesDestroy($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesDestroy'][0])
    {
        $this->organizationsServersSitesRedirectRulesDestroyWithHttpInfo($organization, $server, $site, $redirect_rule, $contentType);
    }

    /**
     * Operation organizationsServersSitesRedirectRulesDestroyWithHttpInfo
     *
     * Delete site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesDestroy'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersSitesRedirectRulesDestroyWithHttpInfo($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesDestroy'][0])
    {
        $request = $this->organizationsServersSitesRedirectRulesDestroyRequest($organization, $server, $site, $redirect_rule, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersSitesRedirectRulesDestroyAsync
     *
     * Delete site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesDestroyAsync($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesDestroy'][0])
    {
        return $this->organizationsServersSitesRedirectRulesDestroyAsyncWithHttpInfo($organization, $server, $site, $redirect_rule, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersSitesRedirectRulesDestroyAsyncWithHttpInfo
     *
     * Delete site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesDestroyAsyncWithHttpInfo($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesDestroy'][0])
    {
        $returnType = '';
        $request = $this->organizationsServersSitesRedirectRulesDestroyRequest($organization, $server, $site, $redirect_rule, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersSitesRedirectRulesDestroy'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesDestroy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersSitesRedirectRulesDestroyRequest($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesDestroy'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersSitesRedirectRulesDestroy'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersSitesRedirectRulesDestroy'
            );
        }

        // verify the required parameter 'site' is set
        if ($site === null || (is_array($site) && count($site) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site when calling organizationsServersSitesRedirectRulesDestroy'
            );
        }

        // verify the required parameter 'redirect_rule' is set
        if ($redirect_rule === null || (is_array($redirect_rule) && count($redirect_rule) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $redirect_rule when calling organizationsServersSitesRedirectRulesDestroy'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/sites/{site}/redirect-rules/{redirectRule}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($site !== null) {
            $resourcePath = str_replace(
                '{site}',
                ObjectSerializer::toPathValue($site),
                $resourcePath
            );
        }
        // path params
        if ($redirect_rule !== null) {
            $resourcePath = str_replace(
                '{redirectRule}',
                ObjectSerializer::toPathValue($redirect_rule),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersSitesRedirectRulesIndex
     *
     * List site redirect rules
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  string|null $sort Available sorts are &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-created_at&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_from The source URL path for the redirect rule. (optional)
     * @param  string|null $filter_to The destination URL path for the redirect rule. (optional)
     * @param  string|null $filter_type The type of the redirect rule. (optional)
     * @param  string|null $filter_status The status of the redirect rule. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesIndex'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesIndex200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject
     */
    public function organizationsServersSitesRedirectRulesIndex($organization, $server, $site, $sort = null, $page_size = 30, $page_cursor = null, $filter_from = null, $filter_to = null, $filter_type = null, $filter_status = null, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesIndex'][0])
    {
        list($response) = $this->organizationsServersSitesRedirectRulesIndexWithHttpInfo($organization, $server, $site, $sort, $page_size, $page_cursor, $filter_from, $filter_to, $filter_type, $filter_status, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersSitesRedirectRulesIndexWithHttpInfo
     *
     * List site redirect rules
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  string|null $sort Available sorts are &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-created_at&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_from The source URL path for the redirect rule. (optional)
     * @param  string|null $filter_to The destination URL path for the redirect rule. (optional)
     * @param  string|null $filter_type The type of the redirect rule. (optional)
     * @param  string|null $filter_status The status of the redirect rule. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesIndex'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesIndex200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersSitesRedirectRulesIndexWithHttpInfo($organization, $server, $site, $sort = null, $page_size = 30, $page_cursor = null, $filter_from = null, $filter_to = null, $filter_type = null, $filter_status = null, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesIndex'][0])
    {
        $request = $this->organizationsServersSitesRedirectRulesIndexRequest($organization, $server, $site, $sort, $page_size, $page_cursor, $filter_from, $filter_to, $filter_type, $filter_status, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesIndex200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesIndex200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesIndex200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersSitesRedirectRulesIndexAsync
     *
     * List site redirect rules
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  string|null $sort Available sorts are &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-created_at&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_from The source URL path for the redirect rule. (optional)
     * @param  string|null $filter_to The destination URL path for the redirect rule. (optional)
     * @param  string|null $filter_type The type of the redirect rule. (optional)
     * @param  string|null $filter_status The status of the redirect rule. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesIndexAsync($organization, $server, $site, $sort = null, $page_size = 30, $page_cursor = null, $filter_from = null, $filter_to = null, $filter_type = null, $filter_status = null, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesIndex'][0])
    {
        return $this->organizationsServersSitesRedirectRulesIndexAsyncWithHttpInfo($organization, $server, $site, $sort, $page_size, $page_cursor, $filter_from, $filter_to, $filter_type, $filter_status, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersSitesRedirectRulesIndexAsyncWithHttpInfo
     *
     * List site redirect rules
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  string|null $sort Available sorts are &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-created_at&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_from The source URL path for the redirect rule. (optional)
     * @param  string|null $filter_to The destination URL path for the redirect rule. (optional)
     * @param  string|null $filter_type The type of the redirect rule. (optional)
     * @param  string|null $filter_status The status of the redirect rule. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesIndexAsyncWithHttpInfo($organization, $server, $site, $sort = null, $page_size = 30, $page_cursor = null, $filter_from = null, $filter_to = null, $filter_type = null, $filter_status = null, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesIndex'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesIndex200Response';
        $request = $this->organizationsServersSitesRedirectRulesIndexRequest($organization, $server, $site, $sort, $page_size, $page_cursor, $filter_from, $filter_to, $filter_type, $filter_status, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersSitesRedirectRulesIndex'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  string|null $sort Available sorts are &#x60;created_at&#x60;, &#x60;updated_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-created_at&#x60;. (optional)
     * @param  int|null $page_size The number of results that will be returned per page. (optional, default to 30)
     * @param  string|null $page_cursor The cursor to start the pagination from. (optional)
     * @param  string|null $filter_from The source URL path for the redirect rule. (optional)
     * @param  string|null $filter_to The destination URL path for the redirect rule. (optional)
     * @param  string|null $filter_type The type of the redirect rule. (optional)
     * @param  string|null $filter_status The status of the redirect rule. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersSitesRedirectRulesIndexRequest($organization, $server, $site, $sort = null, $page_size = 30, $page_cursor = null, $filter_from = null, $filter_to = null, $filter_type = null, $filter_status = null, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesIndex'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersSitesRedirectRulesIndex'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersSitesRedirectRulesIndex'
            );
        }

        // verify the required parameter 'site' is set
        if ($site === null || (is_array($site) && count($site) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site when calling organizationsServersSitesRedirectRulesIndex'
            );
        }









        $resourcePath = '/orgs/{organization}/servers/{server}/sites/{site}/redirect-rules';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page[size]', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_cursor,
            'page[cursor]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_from,
            'filter[from]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_to,
            'filter[to]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_type,
            'filter[type]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_status,
            'filter[status]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($site !== null) {
            $resourcePath = str_replace(
                '{site}',
                ObjectSerializer::toPathValue($site),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersSitesRedirectRulesShow
     *
     * Get site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesShow200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject
     */
    public function organizationsServersSitesRedirectRulesShow($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesShow'][0])
    {
        list($response) = $this->organizationsServersSitesRedirectRulesShowWithHttpInfo($organization, $server, $site, $redirect_rule, $contentType);
        return $response;
    }

    /**
     * Operation organizationsServersSitesRedirectRulesShowWithHttpInfo
     *
     * Get site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesShow'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesShow200Response|\Dimer47\LaravelForgeSdk\Model\InlineObject|\Dimer47\LaravelForgeSdk\Model\InlineObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersSitesRedirectRulesShowWithHttpInfo($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesShow'][0])
    {
        $request = $this->organizationsServersSitesRedirectRulesShowRequest($organization, $server, $site, $redirect_rule, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesShow200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesShow200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesShow200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersSitesRedirectRulesShowAsync
     *
     * Get site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesShowAsync($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesShow'][0])
    {
        return $this->organizationsServersSitesRedirectRulesShowAsyncWithHttpInfo($organization, $server, $site, $redirect_rule, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersSitesRedirectRulesShowAsyncWithHttpInfo
     *
     * Get site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesShowAsyncWithHttpInfo($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesShow'][0])
    {
        $returnType = '\Dimer47\LaravelForgeSdk\Model\OrganizationsServersSitesRedirectRulesShow200Response';
        $request = $this->organizationsServersSitesRedirectRulesShowRequest($organization, $server, $site, $redirect_rule, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersSitesRedirectRulesShow'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  int $redirect_rule The redirect rule ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesShow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersSitesRedirectRulesShowRequest($organization, $server, $site, $redirect_rule, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesShow'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersSitesRedirectRulesShow'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersSitesRedirectRulesShow'
            );
        }

        // verify the required parameter 'site' is set
        if ($site === null || (is_array($site) && count($site) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site when calling organizationsServersSitesRedirectRulesShow'
            );
        }

        // verify the required parameter 'redirect_rule' is set
        if ($redirect_rule === null || (is_array($redirect_rule) && count($redirect_rule) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $redirect_rule when calling organizationsServersSitesRedirectRulesShow'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/sites/{site}/redirect-rules/{redirectRule}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($site !== null) {
            $resourcePath = str_replace(
                '{site}',
                ObjectSerializer::toPathValue($site),
                $resourcePath
            );
        }
        // path params
        if ($redirect_rule !== null) {
            $resourcePath = str_replace(
                '{redirectRule}',
                ObjectSerializer::toPathValue($redirect_rule),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsServersSitesRedirectRulesStore
     *
     * Create site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateRedirectRequest $create_redirect_request create_redirect_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesStore'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function organizationsServersSitesRedirectRulesStore($organization, $server, $site, $create_redirect_request, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesStore'][0])
    {
        $this->organizationsServersSitesRedirectRulesStoreWithHttpInfo($organization, $server, $site, $create_redirect_request, $contentType);
    }

    /**
     * Operation organizationsServersSitesRedirectRulesStoreWithHttpInfo
     *
     * Create site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateRedirectRequest $create_redirect_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesStore'] to see the possible values for this operation
     *
     * @throws \Dimer47\LaravelForgeSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsServersSitesRedirectRulesStoreWithHttpInfo($organization, $server, $site, $create_redirect_request, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesStore'][0])
    {
        $request = $this->organizationsServersSitesRedirectRulesStoreRequest($organization, $server, $site, $create_redirect_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Dimer47\LaravelForgeSdk\Model\InlineObject1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsServersSitesRedirectRulesStoreAsync
     *
     * Create site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateRedirectRequest $create_redirect_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesStoreAsync($organization, $server, $site, $create_redirect_request, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesStore'][0])
    {
        return $this->organizationsServersSitesRedirectRulesStoreAsyncWithHttpInfo($organization, $server, $site, $create_redirect_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsServersSitesRedirectRulesStoreAsyncWithHttpInfo
     *
     * Create site redirect rule
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateRedirectRequest $create_redirect_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsServersSitesRedirectRulesStoreAsyncWithHttpInfo($organization, $server, $site, $create_redirect_request, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesStore'][0])
    {
        $returnType = '';
        $request = $this->organizationsServersSitesRedirectRulesStoreRequest($organization, $server, $site, $create_redirect_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsServersSitesRedirectRulesStore'
     *
     * @param  string $organization The organization slug (required)
     * @param  int $server The server ID (required)
     * @param  int $site The site ID (required)
     * @param  \Dimer47\LaravelForgeSdk\Model\CreateRedirectRequest $create_redirect_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsServersSitesRedirectRulesStore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsServersSitesRedirectRulesStoreRequest($organization, $server, $site, $create_redirect_request, string $contentType = self::contentTypes['organizationsServersSitesRedirectRulesStore'][0])
    {

        // verify the required parameter 'organization' is set
        if ($organization === null || (is_array($organization) && count($organization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization when calling organizationsServersSitesRedirectRulesStore'
            );
        }

        // verify the required parameter 'server' is set
        if ($server === null || (is_array($server) && count($server) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $server when calling organizationsServersSitesRedirectRulesStore'
            );
        }

        // verify the required parameter 'site' is set
        if ($site === null || (is_array($site) && count($site) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $site when calling organizationsServersSitesRedirectRulesStore'
            );
        }

        // verify the required parameter 'create_redirect_request' is set
        if ($create_redirect_request === null || (is_array($create_redirect_request) && count($create_redirect_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_redirect_request when calling organizationsServersSitesRedirectRulesStore'
            );
        }


        $resourcePath = '/orgs/{organization}/servers/{server}/sites/{site}/redirect-rules';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization !== null) {
            $resourcePath = str_replace(
                '{organization}',
                ObjectSerializer::toPathValue($organization),
                $resourcePath
            );
        }
        // path params
        if ($server !== null) {
            $resourcePath = str_replace(
                '{server}',
                ObjectSerializer::toPathValue($server),
                $resourcePath
            );
        }
        // path params
        if ($site !== null) {
            $resourcePath = str_replace(
                '{site}',
                ObjectSerializer::toPathValue($site),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_redirect_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_redirect_request));
            } else {
                $httpBody = $create_redirect_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
