<?php

/**
 * CreateBackgroundProcessRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Model;

use \ArrayAccess;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * CreateBackgroundProcessRequest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateBackgroundProcessRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CreateBackgroundProcessRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'site_id' => 'int',
        'command' => 'string',
        'user' => 'string',
        'directory' => 'string',
        'processes' => 'int',
        'startsecs' => 'int',
        'stopwaitsecs' => 'int',
        'stopsignal' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'site_id' => null,
        'command' => null,
        'user' => null,
        'directory' => null,
        'processes' => null,
        'startsecs' => null,
        'stopwaitsecs' => null,
        'stopsignal' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'site_id' => false,
        'command' => false,
        'user' => false,
        'directory' => true,
        'processes' => false,
        'startsecs' => false,
        'stopwaitsecs' => false,
        'stopsignal' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'site_id' => 'site_id',
        'command' => 'command',
        'user' => 'user',
        'directory' => 'directory',
        'processes' => 'processes',
        'startsecs' => 'startsecs',
        'stopwaitsecs' => 'stopwaitsecs',
        'stopsignal' => 'stopsignal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'site_id' => 'setSiteId',
        'command' => 'setCommand',
        'user' => 'setUser',
        'directory' => 'setDirectory',
        'processes' => 'setProcesses',
        'startsecs' => 'setStartsecs',
        'stopwaitsecs' => 'setStopwaitsecs',
        'stopsignal' => 'setStopsignal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'site_id' => 'getSiteId',
        'command' => 'getCommand',
        'user' => 'getUser',
        'directory' => 'getDirectory',
        'processes' => 'getProcesses',
        'startsecs' => 'getStartsecs',
        'stopwaitsecs' => 'getStopwaitsecs',
        'stopsignal' => 'getStopsignal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const USER_ROOT = 'root';
    public const USER_FORGE = 'forge';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUserAllowableValues()
    {
        return [
            self::USER_ROOT,
            self::USER_FORGE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('site_id', $data ?? [], null);
        $this->setIfExists('command', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('directory', $data ?? [], null);
        $this->setIfExists('processes', $data ?? [], null);
        $this->setIfExists('startsecs', $data ?? [], null);
        $this->setIfExists('stopwaitsecs', $data ?? [], null);
        $this->setIfExists('stopsignal', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['command'] === null) {
            $invalidProperties[] = "'command' can't be null";
        }
        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        $allowedValues = $this->getUserAllowableValues();
        if (!is_null($this->container['user']) && !in_array($this->container['user'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'user', must be one of '%s'",
                $this->container['user'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['processes'] === null) {
            $invalidProperties[] = "'processes' can't be null";
        }
        if (($this->container['processes'] < 1)) {
            $invalidProperties[] = "invalid value for 'processes', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['startsecs']) && ($this->container['startsecs'] < 0)) {
            $invalidProperties[] = "invalid value for 'startsecs', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['stopwaitsecs']) && ($this->container['stopwaitsecs'] < 0)) {
            $invalidProperties[] = "invalid value for 'stopwaitsecs', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the background process.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets site_id
     *
     * @return int|null
     */
    public function getSiteId()
    {
        return $this->container['site_id'];
    }

    /**
     * Sets site_id
     *
     * @param int|null $site_id The site to associate the background process with.
     *
     * @return self
     */
    public function setSiteId($site_id)
    {
        if (is_null($site_id)) {
            throw new \InvalidArgumentException('non-nullable site_id cannot be null');
        }
        $this->container['site_id'] = $site_id;

        return $this;
    }

    /**
     * Gets command
     *
     * @return string
     */
    public function getCommand()
    {
        return $this->container['command'];
    }

    /**
     * Sets command
     *
     * @param string $command The command to run.
     *
     * @return self
     */
    public function setCommand($command)
    {
        if (is_null($command)) {
            throw new \InvalidArgumentException('non-nullable command cannot be null');
        }
        $this->container['command'] = $command;

        return $this;
    }

    /**
     * Gets user
     *
     * @return string
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param string $user The user to run the background process as.
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            throw new \InvalidArgumentException('non-nullable user cannot be null');
        }
        $allowedValues = $this->getUserAllowableValues();
        if (!in_array($user, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'user', must be one of '%s'",
                    $user,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets directory
     *
     * @return string|null
     */
    public function getDirectory()
    {
        return $this->container['directory'];
    }

    /**
     * Sets directory
     *
     * @param string|null $directory The directory to run the background process from.
     *
     * @return self
     */
    public function setDirectory($directory)
    {
        if (is_null($directory)) {
            array_push($this->openAPINullablesSetToNull, 'directory');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('directory', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['directory'] = $directory;

        return $this;
    }

    /**
     * Gets processes
     *
     * @return int
     */
    public function getProcesses()
    {
        return $this->container['processes'];
    }

    /**
     * Sets processes
     *
     * @param int $processes The number of processes to run.
     *
     * @return self
     */
    public function setProcesses($processes)
    {
        if (is_null($processes)) {
            throw new \InvalidArgumentException('non-nullable processes cannot be null');
        }

        if (($processes < 1)) {
            throw new \InvalidArgumentException('invalid value for $processes when calling CreateBackgroundProcessRequest., must be bigger than or equal to 1.');
        }

        $this->container['processes'] = $processes;

        return $this;
    }

    /**
     * Gets startsecs
     *
     * @return int|null
     */
    public function getStartsecs()
    {
        return $this->container['startsecs'];
    }

    /**
     * Sets startsecs
     *
     * @param int|null $startsecs The number of seconds to wait before starting the process.
     *
     * @return self
     */
    public function setStartsecs($startsecs)
    {
        if (is_null($startsecs)) {
            throw new \InvalidArgumentException('non-nullable startsecs cannot be null');
        }

        if (($startsecs < 0)) {
            throw new \InvalidArgumentException('invalid value for $startsecs when calling CreateBackgroundProcessRequest., must be bigger than or equal to 0.');
        }

        $this->container['startsecs'] = $startsecs;

        return $this;
    }

    /**
     * Gets stopwaitsecs
     *
     * @return int|null
     */
    public function getStopwaitsecs()
    {
        return $this->container['stopwaitsecs'];
    }

    /**
     * Sets stopwaitsecs
     *
     * @param int|null $stopwaitsecs The number of seconds to wait before stopping the process.
     *
     * @return self
     */
    public function setStopwaitsecs($stopwaitsecs)
    {
        if (is_null($stopwaitsecs)) {
            throw new \InvalidArgumentException('non-nullable stopwaitsecs cannot be null');
        }

        if (($stopwaitsecs < 0)) {
            throw new \InvalidArgumentException('invalid value for $stopwaitsecs when calling CreateBackgroundProcessRequest., must be bigger than or equal to 0.');
        }

        $this->container['stopwaitsecs'] = $stopwaitsecs;

        return $this;
    }

    /**
     * Gets stopsignal
     *
     * @return string|null
     */
    public function getStopsignal()
    {
        return $this->container['stopsignal'];
    }

    /**
     * Sets stopsignal
     *
     * @param string|null $stopsignal The signal to send to stop the process.
     *
     * @return self
     */
    public function setStopsignal($stopsignal)
    {
        if (is_null($stopsignal)) {
            array_push($this->openAPINullablesSetToNull, 'stopsignal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('stopsignal', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['stopsignal'] = $stopsignal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


