<?php

/**
 * CronFrequency
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Model;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * CronFrequency Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CronFrequency
{
    /**
     * Possible values of this enum
     */
    public const MINUTELY = 'minutely';

    public const HOURLY = 'hourly';

    public const NIGHTLY = 'nightly';

    public const WEEKLY = 'weekly';

    public const MONTHLY = 'monthly';

    public const REBOOT = 'reboot';

    public const CUSTOM = 'custom';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MINUTELY,
            self::HOURLY,
            self::NIGHTLY,
            self::WEEKLY,
            self::MONTHLY,
            self::REBOOT,
            self::CUSTOM
        ];
    }
}


