<?php
/**
 * DomainRecordStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Model;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * DomainRecordStatus Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DomainRecordStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const CONNECTING = 'connecting';

    public const ENABLED = 'enabled';

    public const REMOVING = 'removing';

    public const SECURING = 'securing';

    public const UPDATING = 'updating';

    public const DISABLING = 'disabling';

    public const DISABLED = 'disabled';

    public const ENABLING = 'enabling';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::CONNECTING,
            self::ENABLED,
            self::REMOVING,
            self::SECURING,
            self::UPDATING,
            self::DISABLING,
            self::DISABLED,
            self::ENABLING
        ];
    }
}


