<?php

/**
 * NginxMode
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Model;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * NginxMode Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NginxMode
{
    /**
     * Possible values of this enum
     */
    public const LEGACY = 'legacy';

    public const SPLIT = 'split';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LEGACY,
            self::SPLIT
        ];
    }
}


