<?php
/**
 * ServerResourceAttributes
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Model;

use \ArrayAccess;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * ServerResourceAttributes Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServerResourceAttributes implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ServerResource_attributes';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'credential_id' => 'int',
        'name' => 'string',
        'slug' => 'string',
        'type' => '\Dimer47\LaravelForgeSdk\Model\ServerType',
        'ubuntu_version' => 'string',
        'ssh_port' => 'int',
        'provider' => 'string',
        'identifier' => 'string',
        'size' => 'string',
        'region' => 'string',
        'php_version' => 'string',
        'php_cli_version' => 'string',
        'opcache_status' => 'string',
        'database_type' => 'string',
        'db_status' => 'string',
        'redis_status' => 'string',
        'ip_address' => 'string',
        'private_ip_address' => 'string',
        'revoked' => 'bool',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'connection_status' => 'string',
        'timezone' => 'string',
        'local_public_key' => 'string',
        'is_ready' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'credential_id' => null,
        'name' => null,
        'slug' => null,
        'type' => null,
        'ubuntu_version' => null,
        'ssh_port' => null,
        'provider' => null,
        'identifier' => null,
        'size' => null,
        'region' => null,
        'php_version' => null,
        'php_cli_version' => null,
        'opcache_status' => null,
        'database_type' => null,
        'db_status' => null,
        'redis_status' => null,
        'ip_address' => null,
        'private_ip_address' => null,
        'revoked' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'connection_status' => null,
        'timezone' => null,
        'local_public_key' => null,
        'is_ready' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'credential_id' => true,
        'name' => false,
        'slug' => false,
        'type' => false,
        'ubuntu_version' => true,
        'ssh_port' => false,
        'provider' => false,
        'identifier' => true,
        'size' => false,
        'region' => false,
        'php_version' => true,
        'php_cli_version' => true,
        'opcache_status' => true,
        'database_type' => true,
        'db_status' => true,
        'redis_status' => true,
        'ip_address' => true,
        'private_ip_address' => true,
        'revoked' => false,
        'created_at' => false,
        'updated_at' => false,
        'connection_status' => false,
        'timezone' => false,
        'local_public_key' => true,
        'is_ready' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'credential_id' => 'credential_id',
        'name' => 'name',
        'slug' => 'slug',
        'type' => 'type',
        'ubuntu_version' => 'ubuntu_version',
        'ssh_port' => 'ssh_port',
        'provider' => 'provider',
        'identifier' => 'identifier',
        'size' => 'size',
        'region' => 'region',
        'php_version' => 'php_version',
        'php_cli_version' => 'php_cli_version',
        'opcache_status' => 'opcache_status',
        'database_type' => 'database_type',
        'db_status' => 'db_status',
        'redis_status' => 'redis_status',
        'ip_address' => 'ip_address',
        'private_ip_address' => 'private_ip_address',
        'revoked' => 'revoked',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'connection_status' => 'connection_status',
        'timezone' => 'timezone',
        'local_public_key' => 'local_public_key',
        'is_ready' => 'is_ready'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'credential_id' => 'setCredentialId',
        'name' => 'setName',
        'slug' => 'setSlug',
        'type' => 'setType',
        'ubuntu_version' => 'setUbuntuVersion',
        'ssh_port' => 'setSshPort',
        'provider' => 'setProvider',
        'identifier' => 'setIdentifier',
        'size' => 'setSize',
        'region' => 'setRegion',
        'php_version' => 'setPhpVersion',
        'php_cli_version' => 'setPhpCliVersion',
        'opcache_status' => 'setOpcacheStatus',
        'database_type' => 'setDatabaseType',
        'db_status' => 'setDbStatus',
        'redis_status' => 'setRedisStatus',
        'ip_address' => 'setIpAddress',
        'private_ip_address' => 'setPrivateIpAddress',
        'revoked' => 'setRevoked',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'connection_status' => 'setConnectionStatus',
        'timezone' => 'setTimezone',
        'local_public_key' => 'setLocalPublicKey',
        'is_ready' => 'setIsReady'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'credential_id' => 'getCredentialId',
        'name' => 'getName',
        'slug' => 'getSlug',
        'type' => 'getType',
        'ubuntu_version' => 'getUbuntuVersion',
        'ssh_port' => 'getSshPort',
        'provider' => 'getProvider',
        'identifier' => 'getIdentifier',
        'size' => 'getSize',
        'region' => 'getRegion',
        'php_version' => 'getPhpVersion',
        'php_cli_version' => 'getPhpCliVersion',
        'opcache_status' => 'getOpcacheStatus',
        'database_type' => 'getDatabaseType',
        'db_status' => 'getDbStatus',
        'redis_status' => 'getRedisStatus',
        'ip_address' => 'getIpAddress',
        'private_ip_address' => 'getPrivateIpAddress',
        'revoked' => 'getRevoked',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'connection_status' => 'getConnectionStatus',
        'timezone' => 'getTimezone',
        'local_public_key' => 'getLocalPublicKey',
        'is_ready' => 'getIsReady'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('credential_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('ubuntu_version', $data ?? [], null);
        $this->setIfExists('ssh_port', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('identifier', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('php_version', $data ?? [], null);
        $this->setIfExists('php_cli_version', $data ?? [], null);
        $this->setIfExists('opcache_status', $data ?? [], null);
        $this->setIfExists('database_type', $data ?? [], null);
        $this->setIfExists('db_status', $data ?? [], null);
        $this->setIfExists('redis_status', $data ?? [], null);
        $this->setIfExists('ip_address', $data ?? [], null);
        $this->setIfExists('private_ip_address', $data ?? [], null);
        $this->setIfExists('revoked', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('connection_status', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('local_public_key', $data ?? [], null);
        $this->setIfExists('is_ready', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['credential_id'] === null && !$this->isNullableSetToNull('credential_id')) {
            $invalidProperties[] = "'credential_id' is required";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['ubuntu_version'] === null && !$this->isNullableSetToNull('ubuntu_version')) {
            $invalidProperties[] = "'ubuntu_version' is required";
        }
        if ($this->container['ssh_port'] === null) {
            $invalidProperties[] = "'ssh_port' can't be null";
        }
        if ($this->container['provider'] === null) {
            $invalidProperties[] = "'provider' can't be null";
        }
        if ($this->container['identifier'] === null && !$this->isNullableSetToNull('identifier')) {
            $invalidProperties[] = "'identifier' is required";
        }
        if ($this->container['size'] === null) {
            $invalidProperties[] = "'size' can't be null";
        }
        if ($this->container['region'] === null) {
            $invalidProperties[] = "'region' can't be null";
        }
        if ($this->container['php_version'] === null && !$this->isNullableSetToNull('php_version')) {
            $invalidProperties[] = "'php_version' is required";
        }
        if ($this->container['php_cli_version'] === null && !$this->isNullableSetToNull('php_cli_version')) {
            $invalidProperties[] = "'php_cli_version' is required";
        }
        if ($this->container['opcache_status'] === null && !$this->isNullableSetToNull('opcache_status')) {
            $invalidProperties[] = "'opcache_status' is required";
        }
        if ($this->container['database_type'] === null && !$this->isNullableSetToNull('database_type')) {
            $invalidProperties[] = "'database_type' is required";
        }
        if ($this->container['db_status'] === null && !$this->isNullableSetToNull('db_status')) {
            $invalidProperties[] = "'db_status' is required";
        }
        if ($this->container['redis_status'] === null && !$this->isNullableSetToNull('redis_status')) {
            $invalidProperties[] = "'redis_status' is required";
        }
        if ($this->container['ip_address'] === null && !$this->isNullableSetToNull('ip_address')) {
            $invalidProperties[] = "'ip_address' is required";
        }
        if ($this->container['private_ip_address'] === null && !$this->isNullableSetToNull('private_ip_address')) {
            $invalidProperties[] = "'private_ip_address' is required";
        }
        if ($this->container['revoked'] === null) {
            $invalidProperties[] = "'revoked' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['connection_status'] === null) {
            $invalidProperties[] = "'connection_status' can't be null";
        }
        if ($this->container['timezone'] === null) {
            $invalidProperties[] = "'timezone' can't be null";
        }
        if ($this->container['local_public_key'] === null && !$this->isNullableSetToNull('local_public_key')) {
            $invalidProperties[] = "'local_public_key' is required";
        }
        if ($this->container['is_ready'] === null) {
            $invalidProperties[] = "'is_ready' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets credential_id
     *
     * @return int|null
     */
    public function getCredentialId()
    {
        return $this->container['credential_id'];
    }

    /**
     * Sets credential_id
     *
     * @param int|null $credential_id credential_id
     *
     * @return self
     */
    public function setCredentialId($credential_id)
    {
        if (is_null($credential_id)) {
            array_push($this->openAPINullablesSetToNull, 'credential_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('credential_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['credential_id'] = $credential_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug slug
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Dimer47\LaravelForgeSdk\Model\ServerType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Dimer47\LaravelForgeSdk\Model\ServerType $type The type of server.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets ubuntu_version
     *
     * @return string|null
     */
    public function getUbuntuVersion()
    {
        return $this->container['ubuntu_version'];
    }

    /**
     * Sets ubuntu_version
     *
     * @param string|null $ubuntu_version ubuntu_version
     *
     * @return self
     */
    public function setUbuntuVersion($ubuntu_version)
    {
        if (is_null($ubuntu_version)) {
            array_push($this->openAPINullablesSetToNull, 'ubuntu_version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ubuntu_version', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ubuntu_version'] = $ubuntu_version;

        return $this;
    }

    /**
     * Gets ssh_port
     *
     * @return int
     */
    public function getSshPort()
    {
        return $this->container['ssh_port'];
    }

    /**
     * Sets ssh_port
     *
     * @param int $ssh_port ssh_port
     *
     * @return self
     */
    public function setSshPort($ssh_port)
    {
        if (is_null($ssh_port)) {
            throw new \InvalidArgumentException('non-nullable ssh_port cannot be null');
        }
        $this->container['ssh_port'] = $ssh_port;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return string
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param string $provider provider
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            throw new \InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets identifier
     *
     * @return string|null
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string|null $identifier identifier
     *
     * @return self
     */
    public function setIdentifier($identifier)
    {
        if (is_null($identifier)) {
            array_push($this->openAPINullablesSetToNull, 'identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets size
     *
     * @return string
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param string $size size
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets php_version
     *
     * @return string|null
     */
    public function getPhpVersion()
    {
        return $this->container['php_version'];
    }

    /**
     * Sets php_version
     *
     * @param string|null $php_version php_version
     *
     * @return self
     */
    public function setPhpVersion($php_version)
    {
        if (is_null($php_version)) {
            array_push($this->openAPINullablesSetToNull, 'php_version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('php_version', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['php_version'] = $php_version;

        return $this;
    }

    /**
     * Gets php_cli_version
     *
     * @return string|null
     */
    public function getPhpCliVersion()
    {
        return $this->container['php_cli_version'];
    }

    /**
     * Sets php_cli_version
     *
     * @param string|null $php_cli_version php_cli_version
     *
     * @return self
     */
    public function setPhpCliVersion($php_cli_version)
    {
        if (is_null($php_cli_version)) {
            array_push($this->openAPINullablesSetToNull, 'php_cli_version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('php_cli_version', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['php_cli_version'] = $php_cli_version;

        return $this;
    }

    /**
     * Gets opcache_status
     *
     * @return string|null
     */
    public function getOpcacheStatus()
    {
        return $this->container['opcache_status'];
    }

    /**
     * Sets opcache_status
     *
     * @param string|null $opcache_status opcache_status
     *
     * @return self
     */
    public function setOpcacheStatus($opcache_status)
    {
        if (is_null($opcache_status)) {
            array_push($this->openAPINullablesSetToNull, 'opcache_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('opcache_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['opcache_status'] = $opcache_status;

        return $this;
    }

    /**
     * Gets database_type
     *
     * @return string|null
     */
    public function getDatabaseType()
    {
        return $this->container['database_type'];
    }

    /**
     * Sets database_type
     *
     * @param string|null $database_type database_type
     *
     * @return self
     */
    public function setDatabaseType($database_type)
    {
        if (is_null($database_type)) {
            array_push($this->openAPINullablesSetToNull, 'database_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('database_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['database_type'] = $database_type;

        return $this;
    }

    /**
     * Gets db_status
     *
     * @return string|null
     */
    public function getDbStatus()
    {
        return $this->container['db_status'];
    }

    /**
     * Sets db_status
     *
     * @param string|null $db_status db_status
     *
     * @return self
     */
    public function setDbStatus($db_status)
    {
        if (is_null($db_status)) {
            array_push($this->openAPINullablesSetToNull, 'db_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('db_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['db_status'] = $db_status;

        return $this;
    }

    /**
     * Gets redis_status
     *
     * @return string|null
     */
    public function getRedisStatus()
    {
        return $this->container['redis_status'];
    }

    /**
     * Sets redis_status
     *
     * @param string|null $redis_status redis_status
     *
     * @return self
     */
    public function setRedisStatus($redis_status)
    {
        if (is_null($redis_status)) {
            array_push($this->openAPINullablesSetToNull, 'redis_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redis_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redis_status'] = $redis_status;

        return $this;
    }

    /**
     * Gets ip_address
     *
     * @return string|null
     */
    public function getIpAddress()
    {
        return $this->container['ip_address'];
    }

    /**
     * Sets ip_address
     *
     * @param string|null $ip_address ip_address
     *
     * @return self
     */
    public function setIpAddress($ip_address)
    {
        if (is_null($ip_address)) {
            array_push($this->openAPINullablesSetToNull, 'ip_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ip_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ip_address'] = $ip_address;

        return $this;
    }

    /**
     * Gets private_ip_address
     *
     * @return string|null
     */
    public function getPrivateIpAddress()
    {
        return $this->container['private_ip_address'];
    }

    /**
     * Sets private_ip_address
     *
     * @param string|null $private_ip_address private_ip_address
     *
     * @return self
     */
    public function setPrivateIpAddress($private_ip_address)
    {
        if (is_null($private_ip_address)) {
            array_push($this->openAPINullablesSetToNull, 'private_ip_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('private_ip_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['private_ip_address'] = $private_ip_address;

        return $this;
    }

    /**
     * Gets revoked
     *
     * @return bool
     */
    public function getRevoked()
    {
        return $this->container['revoked'];
    }

    /**
     * Sets revoked
     *
     * @param bool $revoked revoked
     *
     * @return self
     */
    public function setRevoked($revoked)
    {
        if (is_null($revoked)) {
            throw new \InvalidArgumentException('non-nullable revoked cannot be null');
        }
        $this->container['revoked'] = $revoked;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at The date and time the server was created.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at The date and time the server was last updated.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets connection_status
     *
     * @return string
     */
    public function getConnectionStatus()
    {
        return $this->container['connection_status'];
    }

    /**
     * Sets connection_status
     *
     * @param string $connection_status connection_status
     *
     * @return self
     */
    public function setConnectionStatus($connection_status)
    {
        if (is_null($connection_status)) {
            throw new \InvalidArgumentException('non-nullable connection_status cannot be null');
        }
        $this->container['connection_status'] = $connection_status;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone timezone
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets local_public_key
     *
     * @return string|null
     */
    public function getLocalPublicKey()
    {
        return $this->container['local_public_key'];
    }

    /**
     * Sets local_public_key
     *
     * @param string|null $local_public_key local_public_key
     *
     * @return self
     */
    public function setLocalPublicKey($local_public_key)
    {
        if (is_null($local_public_key)) {
            array_push($this->openAPINullablesSetToNull, 'local_public_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('local_public_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['local_public_key'] = $local_public_key;

        return $this;
    }

    /**
     * Gets is_ready
     *
     * @return bool
     */
    public function getIsReady()
    {
        return $this->container['is_ready'];
    }

    /**
     * Sets is_ready
     *
     * @param bool $is_ready is_ready
     *
     * @return self
     */
    public function setIsReady($is_ready)
    {
        if (is_null($is_ready)) {
            throw new \InvalidArgumentException('non-nullable is_ready cannot be null');
        }
        $this->container['is_ready'] = $is_ready;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


