<?php
/**
 * SiteResourceAttributes
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dimer47\LaravelForgeSdk\Model;

use \ArrayAccess;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;

/**
 * SiteResourceAttributes Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SiteResourceAttributes implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SiteResource_attributes';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'status' => '\Dimer47\LaravelForgeSdk\Model\SiteStatus',
        'url' => 'string',
        'user' => 'string',
        'https' => 'bool',
        'web_directory' => 'string',
        'root_directory' => 'string',
        'aliases' => 'mixed[]',
        'php_version' => 'string',
        'deployment_status' => 'string',
        'quick_deploy' => 'bool',
        'isolated' => 'bool',
        'shared_paths' => 'array<string,string>',
        'repository' => '\Dimer47\LaravelForgeSdk\Model\SiteResourceAttributesRepository',
        'database' => 'string',
        'maintenance_mode' => '\Dimer47\LaravelForgeSdk\Model\SiteResourceAttributesMaintenanceMode',
        'zero_downtime_deployments' => 'bool',
        'deployment_script' => 'string',
        'wildcards' => 'bool',
        'app_type' => 'string',
        'uses_envoyer' => 'bool',
        'deployment_url' => 'string',
        'healthcheck_url' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'status' => null,
        'url' => null,
        'user' => null,
        'https' => null,
        'web_directory' => null,
        'root_directory' => null,
        'aliases' => null,
        'php_version' => null,
        'deployment_status' => null,
        'quick_deploy' => null,
        'isolated' => null,
        'shared_paths' => null,
        'repository' => null,
        'database' => null,
        'maintenance_mode' => null,
        'zero_downtime_deployments' => null,
        'deployment_script' => null,
        'wildcards' => null,
        'app_type' => null,
        'uses_envoyer' => null,
        'deployment_url' => null,
        'healthcheck_url' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'status' => false,
        'url' => false,
        'user' => false,
        'https' => false,
        'web_directory' => false,
        'root_directory' => true,
        'aliases' => false,
        'php_version' => false,
        'deployment_status' => false,
        'quick_deploy' => true,
        'isolated' => false,
        'shared_paths' => false,
        'repository' => false,
        'database' => true,
        'maintenance_mode' => false,
        'zero_downtime_deployments' => false,
        'deployment_script' => true,
        'wildcards' => true,
        'app_type' => true,
        'uses_envoyer' => false,
        'deployment_url' => false,
        'healthcheck_url' => true,
        'created_at' => true,
        'updated_at' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'status' => 'status',
        'url' => 'url',
        'user' => 'user',
        'https' => 'https',
        'web_directory' => 'web_directory',
        'root_directory' => 'root_directory',
        'aliases' => 'aliases',
        'php_version' => 'php_version',
        'deployment_status' => 'deployment_status',
        'quick_deploy' => 'quick_deploy',
        'isolated' => 'isolated',
        'shared_paths' => 'shared_paths',
        'repository' => 'repository',
        'database' => 'database',
        'maintenance_mode' => 'maintenance_mode',
        'zero_downtime_deployments' => 'zero_downtime_deployments',
        'deployment_script' => 'deployment_script',
        'wildcards' => 'wildcards',
        'app_type' => 'app_type',
        'uses_envoyer' => 'uses_envoyer',
        'deployment_url' => 'deployment_url',
        'healthcheck_url' => 'healthcheck_url',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'status' => 'setStatus',
        'url' => 'setUrl',
        'user' => 'setUser',
        'https' => 'setHttps',
        'web_directory' => 'setWebDirectory',
        'root_directory' => 'setRootDirectory',
        'aliases' => 'setAliases',
        'php_version' => 'setPhpVersion',
        'deployment_status' => 'setDeploymentStatus',
        'quick_deploy' => 'setQuickDeploy',
        'isolated' => 'setIsolated',
        'shared_paths' => 'setSharedPaths',
        'repository' => 'setRepository',
        'database' => 'setDatabase',
        'maintenance_mode' => 'setMaintenanceMode',
        'zero_downtime_deployments' => 'setZeroDowntimeDeployments',
        'deployment_script' => 'setDeploymentScript',
        'wildcards' => 'setWildcards',
        'app_type' => 'setAppType',
        'uses_envoyer' => 'setUsesEnvoyer',
        'deployment_url' => 'setDeploymentUrl',
        'healthcheck_url' => 'setHealthcheckUrl',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'status' => 'getStatus',
        'url' => 'getUrl',
        'user' => 'getUser',
        'https' => 'getHttps',
        'web_directory' => 'getWebDirectory',
        'root_directory' => 'getRootDirectory',
        'aliases' => 'getAliases',
        'php_version' => 'getPhpVersion',
        'deployment_status' => 'getDeploymentStatus',
        'quick_deploy' => 'getQuickDeploy',
        'isolated' => 'getIsolated',
        'shared_paths' => 'getSharedPaths',
        'repository' => 'getRepository',
        'database' => 'getDatabase',
        'maintenance_mode' => 'getMaintenanceMode',
        'zero_downtime_deployments' => 'getZeroDowntimeDeployments',
        'deployment_script' => 'getDeploymentScript',
        'wildcards' => 'getWildcards',
        'app_type' => 'getAppType',
        'uses_envoyer' => 'getUsesEnvoyer',
        'deployment_url' => 'getDeploymentUrl',
        'healthcheck_url' => 'getHealthcheckUrl',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const APP_TYPE_STATAMIC = 'Statamic';
    public const APP_TYPE_WORD_PRESS = 'WordPress';
    public const APP_TYPE_PHP_MY_ADMIN = 'phpMyAdmin';
    public const APP_TYPE_LARAVEL = 'Laravel';
    public const APP_TYPE_SYMFONY = 'Symfony';
    public const APP_TYPE_PHP = 'PHP';
    public const APP_TYPE_NEXT_JS = 'Next.js';
    public const APP_TYPE_NUXT_JS = 'Nuxt.js';
    public const APP_TYPE_STATIC_HTML = 'Static HTML';
    public const APP_TYPE_CUSTOM = 'Custom';
    public const APP_TYPE_CRAFT = 'Craft';
    public const APP_TYPE_MINECRAFT = 'Minecraft';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAppTypeAllowableValues()
    {
        return [
            self::APP_TYPE_STATAMIC,
            self::APP_TYPE_WORD_PRESS,
            self::APP_TYPE_PHP_MY_ADMIN,
            self::APP_TYPE_LARAVEL,
            self::APP_TYPE_SYMFONY,
            self::APP_TYPE_PHP,
            self::APP_TYPE_NEXT_JS,
            self::APP_TYPE_NUXT_JS,
            self::APP_TYPE_STATIC_HTML,
            self::APP_TYPE_CUSTOM,
            self::APP_TYPE_CRAFT,
            self::APP_TYPE_MINECRAFT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('https', $data ?? [], null);
        $this->setIfExists('web_directory', $data ?? [], null);
        $this->setIfExists('root_directory', $data ?? [], null);
        $this->setIfExists('aliases', $data ?? [], null);
        $this->setIfExists('php_version', $data ?? [], null);
        $this->setIfExists('deployment_status', $data ?? [], null);
        $this->setIfExists('quick_deploy', $data ?? [], null);
        $this->setIfExists('isolated', $data ?? [], null);
        $this->setIfExists('shared_paths', $data ?? [], null);
        $this->setIfExists('repository', $data ?? [], null);
        $this->setIfExists('database', $data ?? [], null);
        $this->setIfExists('maintenance_mode', $data ?? [], null);
        $this->setIfExists('zero_downtime_deployments', $data ?? [], null);
        $this->setIfExists('deployment_script', $data ?? [], null);
        $this->setIfExists('wildcards', $data ?? [], null);
        $this->setIfExists('app_type', $data ?? [], null);
        $this->setIfExists('uses_envoyer', $data ?? [], null);
        $this->setIfExists('deployment_url', $data ?? [], null);
        $this->setIfExists('healthcheck_url', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        if ($this->container['https'] === null) {
            $invalidProperties[] = "'https' can't be null";
        }
        if ($this->container['web_directory'] === null) {
            $invalidProperties[] = "'web_directory' can't be null";
        }
        if ($this->container['root_directory'] === null && !$this->isNullableSetToNull('root_directory')) {
            $invalidProperties[] = "'root_directory' is required";
        }
        if ($this->container['aliases'] === null) {
            $invalidProperties[] = "'aliases' can't be null";
        }
        if ($this->container['php_version'] === null) {
            $invalidProperties[] = "'php_version' can't be null";
        }
        if ($this->container['deployment_status'] === null) {
            $invalidProperties[] = "'deployment_status' can't be null";
        }
        if ($this->container['quick_deploy'] === null && !$this->isNullableSetToNull('quick_deploy')) {
            $invalidProperties[] = "'quick_deploy' is required";
        }
        if ($this->container['isolated'] === null) {
            $invalidProperties[] = "'isolated' can't be null";
        }
        if ($this->container['shared_paths'] === null) {
            $invalidProperties[] = "'shared_paths' can't be null";
        }
        if ($this->container['repository'] === null) {
            $invalidProperties[] = "'repository' can't be null";
        }
        if ($this->container['database'] === null && !$this->isNullableSetToNull('database')) {
            $invalidProperties[] = "'database' is required";
        }
        if ($this->container['maintenance_mode'] === null) {
            $invalidProperties[] = "'maintenance_mode' can't be null";
        }
        if ($this->container['zero_downtime_deployments'] === null) {
            $invalidProperties[] = "'zero_downtime_deployments' can't be null";
        }
        if ($this->container['deployment_script'] === null && !$this->isNullableSetToNull('deployment_script')) {
            $invalidProperties[] = "'deployment_script' is required";
        }
        if ($this->container['wildcards'] === null && !$this->isNullableSetToNull('wildcards')) {
            $invalidProperties[] = "'wildcards' is required";
        }
        if ($this->container['app_type'] === null && !$this->isNullableSetToNull('app_type')) {
            $invalidProperties[] = "'app_type' is required";
        }
        $allowedValues = $this->getAppTypeAllowableValues();
        if (!is_null($this->container['app_type']) && !in_array($this->container['app_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'app_type', must be one of '%s'",
                $this->container['app_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['uses_envoyer'] === null) {
            $invalidProperties[] = "'uses_envoyer' can't be null";
        }
        if ($this->container['deployment_url'] === null) {
            $invalidProperties[] = "'deployment_url' can't be null";
        }
        if ($this->container['healthcheck_url'] === null && !$this->isNullableSetToNull('healthcheck_url')) {
            $invalidProperties[] = "'healthcheck_url' is required";
        }
        if ($this->container['created_at'] === null && !$this->isNullableSetToNull('created_at')) {
            $invalidProperties[] = "'created_at' is required";
        }
        if ($this->container['updated_at'] === null && !$this->isNullableSetToNull('updated_at')) {
            $invalidProperties[] = "'updated_at' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Dimer47\LaravelForgeSdk\Model\SiteStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Dimer47\LaravelForgeSdk\Model\SiteStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets user
     *
     * @return string
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param string $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            throw new \InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets https
     *
     * @return bool
     */
    public function getHttps()
    {
        return $this->container['https'];
    }

    /**
     * Sets https
     *
     * @param bool $https https
     *
     * @return self
     */
    public function setHttps($https)
    {
        if (is_null($https)) {
            throw new \InvalidArgumentException('non-nullable https cannot be null');
        }
        $this->container['https'] = $https;

        return $this;
    }

    /**
     * Gets web_directory
     *
     * @return string
     */
    public function getWebDirectory()
    {
        return $this->container['web_directory'];
    }

    /**
     * Sets web_directory
     *
     * @param string $web_directory web_directory
     *
     * @return self
     */
    public function setWebDirectory($web_directory)
    {
        if (is_null($web_directory)) {
            throw new \InvalidArgumentException('non-nullable web_directory cannot be null');
        }
        $this->container['web_directory'] = $web_directory;

        return $this;
    }

    /**
     * Gets root_directory
     *
     * @return string|null
     */
    public function getRootDirectory()
    {
        return $this->container['root_directory'];
    }

    /**
     * Sets root_directory
     *
     * @param string|null $root_directory root_directory
     *
     * @return self
     */
    public function setRootDirectory($root_directory)
    {
        if (is_null($root_directory)) {
            array_push($this->openAPINullablesSetToNull, 'root_directory');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('root_directory', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['root_directory'] = $root_directory;

        return $this;
    }

    /**
     * Gets aliases
     *
     * @return mixed[]
     */
    public function getAliases()
    {
        return $this->container['aliases'];
    }

    /**
     * Sets aliases
     *
     * @param mixed[] $aliases aliases
     *
     * @return self
     */
    public function setAliases($aliases)
    {
        if (is_null($aliases)) {
            throw new \InvalidArgumentException('non-nullable aliases cannot be null');
        }
        $this->container['aliases'] = $aliases;

        return $this;
    }

    /**
     * Gets php_version
     *
     * @return string
     */
    public function getPhpVersion()
    {
        return $this->container['php_version'];
    }

    /**
     * Sets php_version
     *
     * @param string $php_version php_version
     *
     * @return self
     */
    public function setPhpVersion($php_version)
    {
        if (is_null($php_version)) {
            throw new \InvalidArgumentException('non-nullable php_version cannot be null');
        }
        $this->container['php_version'] = $php_version;

        return $this;
    }

    /**
     * Gets deployment_status
     *
     * @return string
     */
    public function getDeploymentStatus()
    {
        return $this->container['deployment_status'];
    }

    /**
     * Sets deployment_status
     *
     * @param string $deployment_status deployment_status
     *
     * @return self
     */
    public function setDeploymentStatus($deployment_status)
    {
        if (is_null($deployment_status)) {
            throw new \InvalidArgumentException('non-nullable deployment_status cannot be null');
        }
        $this->container['deployment_status'] = $deployment_status;

        return $this;
    }

    /**
     * Gets quick_deploy
     *
     * @return bool|null
     */
    public function getQuickDeploy()
    {
        return $this->container['quick_deploy'];
    }

    /**
     * Sets quick_deploy
     *
     * @param bool|null $quick_deploy quick_deploy
     *
     * @return self
     */
    public function setQuickDeploy($quick_deploy)
    {
        if (is_null($quick_deploy)) {
            array_push($this->openAPINullablesSetToNull, 'quick_deploy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('quick_deploy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['quick_deploy'] = $quick_deploy;

        return $this;
    }

    /**
     * Gets isolated
     *
     * @return bool
     */
    public function getIsolated()
    {
        return $this->container['isolated'];
    }

    /**
     * Sets isolated
     *
     * @param bool $isolated isolated
     *
     * @return self
     */
    public function setIsolated($isolated)
    {
        if (is_null($isolated)) {
            throw new \InvalidArgumentException('non-nullable isolated cannot be null');
        }
        $this->container['isolated'] = $isolated;

        return $this;
    }

    /**
     * Gets shared_paths
     *
     * @return array<string,string>
     */
    public function getSharedPaths()
    {
        return $this->container['shared_paths'];
    }

    /**
     * Sets shared_paths
     *
     * @param array<string,string> $shared_paths * The linked directories for the site.
     *
     * @return self
     */
    public function setSharedPaths($shared_paths)
    {
        if (is_null($shared_paths)) {
            throw new \InvalidArgumentException('non-nullable shared_paths cannot be null');
        }
        $this->container['shared_paths'] = $shared_paths;

        return $this;
    }

    /**
     * Gets repository
     *
     * @return \Dimer47\LaravelForgeSdk\Model\SiteResourceAttributesRepository
     */
    public function getRepository()
    {
        return $this->container['repository'];
    }

    /**
     * Sets repository
     *
     * @param \Dimer47\LaravelForgeSdk\Model\SiteResourceAttributesRepository $repository repository
     *
     * @return self
     */
    public function setRepository($repository)
    {
        if (is_null($repository)) {
            throw new \InvalidArgumentException('non-nullable repository cannot be null');
        }
        $this->container['repository'] = $repository;

        return $this;
    }

    /**
     * Gets database
     *
     * @return string|null
     */
    public function getDatabase()
    {
        return $this->container['database'];
    }

    /**
     * Sets database
     *
     * @param string|null $database database
     *
     * @return self
     */
    public function setDatabase($database)
    {
        if (is_null($database)) {
            array_push($this->openAPINullablesSetToNull, 'database');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('database', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['database'] = $database;

        return $this;
    }

    /**
     * Gets maintenance_mode
     *
     * @return \Dimer47\LaravelForgeSdk\Model\SiteResourceAttributesMaintenanceMode
     */
    public function getMaintenanceMode()
    {
        return $this->container['maintenance_mode'];
    }

    /**
     * Sets maintenance_mode
     *
     * @param \Dimer47\LaravelForgeSdk\Model\SiteResourceAttributesMaintenanceMode $maintenance_mode maintenance_mode
     *
     * @return self
     */
    public function setMaintenanceMode($maintenance_mode)
    {
        if (is_null($maintenance_mode)) {
            throw new \InvalidArgumentException('non-nullable maintenance_mode cannot be null');
        }
        $this->container['maintenance_mode'] = $maintenance_mode;

        return $this;
    }

    /**
     * Gets zero_downtime_deployments
     *
     * @return bool
     */
    public function getZeroDowntimeDeployments()
    {
        return $this->container['zero_downtime_deployments'];
    }

    /**
     * Sets zero_downtime_deployments
     *
     * @param bool $zero_downtime_deployments zero_downtime_deployments
     *
     * @return self
     */
    public function setZeroDowntimeDeployments($zero_downtime_deployments)
    {
        if (is_null($zero_downtime_deployments)) {
            throw new \InvalidArgumentException('non-nullable zero_downtime_deployments cannot be null');
        }
        $this->container['zero_downtime_deployments'] = $zero_downtime_deployments;

        return $this;
    }

    /**
     * Gets deployment_script
     *
     * @return string|null
     */
    public function getDeploymentScript()
    {
        return $this->container['deployment_script'];
    }

    /**
     * Sets deployment_script
     *
     * @param string|null $deployment_script deployment_script
     *
     * @return self
     */
    public function setDeploymentScript($deployment_script)
    {
        if (is_null($deployment_script)) {
            array_push($this->openAPINullablesSetToNull, 'deployment_script');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deployment_script', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deployment_script'] = $deployment_script;

        return $this;
    }

    /**
     * Gets wildcards
     *
     * @return bool|null
     */
    public function getWildcards()
    {
        return $this->container['wildcards'];
    }

    /**
     * Sets wildcards
     *
     * @param bool|null $wildcards wildcards
     *
     * @return self
     */
    public function setWildcards($wildcards)
    {
        if (is_null($wildcards)) {
            array_push($this->openAPINullablesSetToNull, 'wildcards');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wildcards', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['wildcards'] = $wildcards;

        return $this;
    }

    /**
     * Gets app_type
     *
     * @return string|null
     */
    public function getAppType()
    {
        return $this->container['app_type'];
    }

    /**
     * Sets app_type
     *
     * @param string|null $app_type app_type
     *
     * @return self
     */
    public function setAppType($app_type)
    {
        if (is_null($app_type)) {
            array_push($this->openAPINullablesSetToNull, 'app_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('app_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getAppTypeAllowableValues();
        if (!is_null($app_type) && !in_array($app_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'app_type', must be one of '%s'",
                    $app_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['app_type'] = $app_type;

        return $this;
    }

    /**
     * Gets uses_envoyer
     *
     * @return bool
     */
    public function getUsesEnvoyer()
    {
        return $this->container['uses_envoyer'];
    }

    /**
     * Sets uses_envoyer
     *
     * @param bool $uses_envoyer uses_envoyer
     *
     * @return self
     */
    public function setUsesEnvoyer($uses_envoyer)
    {
        if (is_null($uses_envoyer)) {
            throw new \InvalidArgumentException('non-nullable uses_envoyer cannot be null');
        }
        $this->container['uses_envoyer'] = $uses_envoyer;

        return $this;
    }

    /**
     * Gets deployment_url
     *
     * @return string
     */
    public function getDeploymentUrl()
    {
        return $this->container['deployment_url'];
    }

    /**
     * Sets deployment_url
     *
     * @param string $deployment_url deployment_url
     *
     * @return self
     */
    public function setDeploymentUrl($deployment_url)
    {
        if (is_null($deployment_url)) {
            throw new \InvalidArgumentException('non-nullable deployment_url cannot be null');
        }
        $this->container['deployment_url'] = $deployment_url;

        return $this;
    }

    /**
     * Gets healthcheck_url
     *
     * @return string|null
     */
    public function getHealthcheckUrl()
    {
        return $this->container['healthcheck_url'];
    }

    /**
     * Sets healthcheck_url
     *
     * @param string|null $healthcheck_url healthcheck_url
     *
     * @return self
     */
    public function setHealthcheckUrl($healthcheck_url)
    {
        if (is_null($healthcheck_url)) {
            array_push($this->openAPINullablesSetToNull, 'healthcheck_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('healthcheck_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['healthcheck_url'] = $healthcheck_url;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            array_push($this->openAPINullablesSetToNull, 'created_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            array_push($this->openAPINullablesSetToNull, 'updated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updated_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


